### PR TITLE
Better CommCare support (check endpoint, allow paths)

### LINKED ISSUE #1063: Consider adding a `GET` endpoint to check if webhooks exist
Some (at least one???) external services require that before sending data to a webhook URL via a POST request they first must be able "check" if that webhook URL is valid by sending a GET request. 

See Mailchimp: https://mailchimp.com/developer/marketing/guides/run-async-requests-batch-endpoint/#batch-webhooks

image

Is this something we're interested in supporting on Lightning?

(FYI @mtuchi )

### LINKED ISSUE #1954: Add support for paths and query params
Certain systems (especially CommCare) append key data as part of a `path` _after_ the webhook URL. While this isn't exactly standard, we should be able to provide users additional path data (like in pipedream) when they send it. Additionally, we should show users any query params that they add to the webhook URL

### PR DESCRIPTION
**Pull request by taylordowns2000**
Fixes #1063 and Fixes #1954

@aleksa-krolls , this was a <10 min change so i've opened a placeholder PR. have tested manually and works like a charm. would like @stuartc 's general reaction before writing tests

## Validation Steps

coming soon...

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

### CODE REVIEW

**Comment by taylordowns2000** [comment]
@stuartc , would like your general reaction to allowing `paths` and providing a `GET` endpoint for webhook "testing" before writing up the tests here. all manual testing has been 👍

**Review by christad92 — APPROVED** [review]
I have tested this in a few ways and it feels really GOOD. I like that it allows users to be able to dynamically inject values/conditions into their workflows. 

Looks good to me.

**Review by stuartc — CHANGES_REQUESTED** [review]
Please write a test for the query params that are added to the request data.

**Comment by taylordowns2000** [comment]
> Please write a test for the query params that are added to the request data.

done! thanks @stuartc

**Pull request merged**
