### PR TITLE
Fix code assist modules

### LINKED ISSUE #2641: Intellisense seems to be broken (see magic function for DHIS2)
When using the DHIS2 adaptor with the credentials well configured and metadata loaded, the IntelliSense did not load. Even when you try to manually trigger it by entering ctrl/cmd + space, it doesn't load.

### PR DESCRIPTION
**Pull request by josephjclark**
### Description

This PR fixes an issue where code assist is not available for the second argument of dhis2.create.

Closes #2641

Improves #2627

### Implementation nodes

Global types declared in an adaptor's `types.d.ts` are not made visible to each adaptor in Monaco, as a result of changes made in #2433 where each file is loaded into its own module.

We've also got problems where functions which are not exported from an adaptor are exposed as code-complete suggestions. 

I've had to do a bunch of things:

* Everything from common is loaded into a single uber-module called `@openfn/language-common`. None of these definitions are exposed globally to the script.
* BUT imports from `@openfn/common` now work organically inside our adaptor's typings, so this is good
* The main adaptor loads each file into its own module, like `@openfn/language-dhis2/Util.d.ts`. These are also scoped and not available globally
* EXCEPT for index.d.ts and adaptor.d.ts. These are loaded into the global namespace, which means all main adaptor exports and namespaces declared in index.d.ts are loaded globally and available to the user
* To make this work in Monaco, we have to do some nasty regex refactoring of the code (see commends in `Editor.tsx:154`-ish)
* This gives us a much more realistic projection of the adaptor's types into Monaco
* BUT global types still won't load. In Adaptor.d.ts we refer to `Dhis2Data`, a "global" type which, because of how we load modules, is loaded into its own private scope. So after all this work, `dhis2` still doesn't work.
* As a workaround, we force the contents of global types in `types.d.ts` into each module scope.

And this works! :tada: 

Note that global types in other d.ts files still won't work. I've hard-coded support for `types.d.ts`.

### QA

I really need help with QA on this!

First, please test dhis2.

Load up a dhis2 job and type `create('trackedEntityInstance', {})`. You should get code assist on the object. You do NOT need metadata or a valid credential (but if you have one, you should get smart metadata too).

Then please test around some other adaptors.

- Pick an adaptor
- Open its adaptor docs in a new window
- Check that functions and namespaces exported by that adaptor are available in code assist
- You might also check whether you get code assist on the arguments to each function (many adaptors will not)
- Check that functions from common are not exported (unless the adaptor explicitly exports them)

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### CODE REVIEW

**Comment by josephjclark** [comment]
For DHIS2 I get a decent list of suggested functions:

image

And I get code assist on the object of `create`:

image

**Comment by josephjclark** [comment]
For `fhir-ndr-et` - which has some hairy code assist stuff, I get reasonable top level suggestions:

image

I get code assist on profile names:

image

And I get code assist on Patient properties:

image

I do NOT get code assist on resources with multiple profiles, but  this is a known issue

**Comment by josephjclark** [comment]
In common I get code assist for http.get:

image

Although I do not see `http` listed at the top level :thinking: 

image

I do not get code assist on http.options  - but I don't in production

image

That's a bit wierd because there IS a typing in the d.ts file

**Comment by josephjclark** [comment]
Ah, I think the problem in common is that I'm loading common/util/http.d.ts (which is not well typed) and overwriting common/http.d.ts, which IS.  There's sort of a naming conflict. I might try ti fix this here tomorrow.

**Comment by josephjclark** [comment]
We also don't get typings on http's params argument.

but that's because the d.ts file is basically broken:
```
export type RequestOptions = any;
```
This is a bit of a problem - we should be able to provide good code assist on this stuff.

Sigh.

**Review by stuartc — APPROVED** [review]
Works locally for me, this seems pretty reasonable for now and the logic is nicely commented and isolated 👌

**Pull request merged**
