### PR TITLE
Ai service

### LINKED ISSUE #2193: Implement Job Writing AI Assistant
We have implemented an AI service that can help users write better job codes or find wrong patterns in their job codes by providing simple prompts and we want to integrate this with Lightning.

As a user, on the editor page, 
- [ ] I want to click on the AI assistant tab, enter my prompts, and get relevant guidance or snippets for my code based on the OpenFn Adaptor documentation. 
- [ ] I would also like to see my previously asked questions via a history feature on the page. This list of previously asked questions should also be searchable. 

Design: https://www.figma.com/design/4hGWdO4sajnjcOwE81j8BK/App-(new)?node-id=4492-680&t=sEmPLXFk5O3YAVwy-0

This is related to https://github.com/OpenFn/apollo/issues/52

### PR DESCRIPTION
**Pull request by stuartc**
## Validation Steps

- Run the app with the appropriate env vars:

`OPENAI_API_KEY`, your OpenAI API key.
`APOLLO_ENDPOINT`, can use `https://apollo.staging.openfn.org/`.

Log in as a superuser, and go to edit a job - you should have the AI assistant menu item available.

## Notes for the reviewer

There is no chat persistence between page navigation or reloads.

## Related issue

Fixes #2193

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
looks great @stuartc and @midigofrank .

1. After rebase, please double check that the "Inspect this step" links from both the History interface and the RunView interface take the user to the Inspector with the **Log** tab open on the right panel.
2. When clicking "run" from the middle panel, I notice that the AI chat panel gets wiped clear. (I also notice that the input panel _flashes_ unexpectedly and then comes back.) Can you look into this?

**Comment by midigofrank** [comment]
> 2. When clicking "run" from the middle panel, I notice that the AI chat panel gets wiped clear. (I also notice that the input panel _flashes_ unexpectedly and then comes back.) Can you look into this?

@stuartc I think the chat gets cleared because the `update` callback of the `LiveComponent` gets called after the `LiveView` `handle_params` and that creates a new session

**Comment by stuartc** [comment]
@midigofrank @taylordowns2000 I've fixed the wiping of the chat state on clicking run here: https://github.com/OpenFn/lightning/pull/2216/commits/8363a28bf9f17585d58ea37edf4a2bc702ad65f6

**Review by taylordowns2000 — APPROVED** [review]
both the requested changes have been addressed! good to go from me!

image

**Pull request merged**
