### PR TITLE
Collections Datastore

### PR DESCRIPTION
**Pull request by stuartc**
### Description

This PR *[adds/changes/fixes]... (A description of your work goes here.)*

Re: [#2190](https://github.com/OpenFn/lightning/issues/2190)

Spec: #2566

### Validation steps

1. *(How can a reviewer validate your work?)*

### Additional notes for the reviewer

1. *(Is there anything else the reviewer should know or look out for?)*

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [ ] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

**Comment by josephjclark** [comment]
So far as I understand it the following still needs doing:
* [ ] POST should return 200/201
* [ ] DELETE does not support key patterns
* [ ] Support for `created_at` etc query parameters on GET and DELETE
* [ ] Support for `created_at` metadata in the database
* [ ] Rename `upserts` to `upserted`  ?

Any of these that we don't plan to do before release need to be spun out into new issues

And I'm seeing these issues on my local branch:

* GET with a key returns `{ key, value }`, not `{ items: [{ key, value }] }`
* I don't think key patterns are actually working at all (I'm investigating as I type)

**Comment by josephjclark** [comment]
Yes Ok, to confirm some issues:

`curl -X GET localhost:4000/collections/stuff/a` incorrectly returns ` { value, key }` (it should be in an items array for consistency

` curl -X GET localhost:4000/collections/stuff/*` incorrectly returns `{ error: "item not found" }`. But I expect a pattern search here (this is basically get all)

`curl -X GET localhost:4000/collections/stuff/` correctly returns `{ items, cursor }`

**Comment by stuartc** [comment]
- [ ] Support for `?limit=x` in the parameters.
- [ ] Support for `created_[after|before]`, `updated_[after|before]`
- [ ] Change cursor to work on `inserted_at` by default.

**Comment by stuartc** [comment]
```
get /collections/openhie?key="a*" -> stream_match
get /collections/openhie?key="a*"&created_at=2024-10-31
```

☝️ @jyeshe

**Comment by stuartc** [comment]
> Yes Ok, to confirm some issues:
> 
> `curl -X GET localhost:4000/collections/stuff/a` incorrectly returns ` { value, key }` (it should be in an items array for consistency
> 
> ` curl -X GET localhost:4000/collections/stuff/*` incorrectly returns `{ error: "item not found" }`. But I expect a pattern search here (this is basically get all)
> 
> `curl -X GET localhost:4000/collections/stuff/` correctly returns `{ items, cursor }`

@josephjclark so I've merged in the changes by @jyeshe and added a test.

To confirm from our conversation yesterday, what is implemented now is:

> `curl -X GET localhost:4000/collections/stuff/a` returns `{ value, key }`
> `curl -X GET localhost:4000/collections/stuff?key=*` should return `{ items: [...], cursor: String|null }`.

**Comment by josephjclark** [comment]
I'm getting a 404 for `DELETE collections/<name>`
```
 curl -X DELETE localhost:4000/collections/demo/ -H "authorization: Bearer $LIGHTNING_API_KEY"
```
The error comes back as rich HTML page but the key line is:
```
 Phoenix.Router.NoRouteError at DELETE /collections/demo/
```

**Comment by josephjclark** [comment]
A reminder: the Worker now needs to know where the Collections server is, otherwise it won't add collections credentials to Runs and they'll all fail.

We need to set the `WORKER_COLLECTIONS_URL` env var to eg `app.openfn.org/collections`.

Also, the worker will lookup the latest collections adaptor version when it starts up, and use that through its lifetime. If we want to, we can set a fixed version in the worker env through `WORKER_COLLECTIONS_VERSION` (this is probably more useful for local dev than for production)

**Pull request merged**
