### PR TITLE
Distinguish active and inactive sort arrows in projects overview table

### LINKED ISSUE #2423: Both sort arrows are appearing at once on the projects table
Two small things here:
1. The main thing is that this list is sorted by name, not by last activity. (But it looks like it's sorted by.... both?) Check out how the arrows [should appear on hover](https://tailwindui.com/components/application-ui/lists/tables#component-7b5a46e74e475708d966ca31716f1771) or if that's the sort order. They shouldn't appear if they're not actually controlling the sort of the table. (Tailwind and Google Drive both have good examples of how this should work.)
2. The arrows are upside down! Chevron-down should indicate a descending sort order. Chevron-up should indicate an ascending sort order.

image

### PR DESCRIPTION
**Pull request by midigofrank**
### Description

This PR makes the active and inactive sort arrows in projects overview table distinguishable.

When the column is actively being sorted, the icon has a `bg`. If it's inactive, the opacity falls to 50% 

I have also moved handling of the sort params to the context. It felt weird having to handle `nulls last` in the liveview code

Closes #2423

### Validation steps

Screenshot 2024-11-18 at 10 21 24

### Additional notes for the reviewer

I'm kinda not sure if I have the correct direction for the `chevron-icon`. Might need a keen eye there

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

**Review by elias-ba — APPROVED** [review]
@midigofrank this is really nice, I love the `table_sort_icon/1` component, great job.

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
Fantastic. 2 changes requested here: https://www.loom.com/share/89535d108635482c98b71dfd57bb40c4

1. only show sort icon on hover if the sort is not active
2. make the whole heading clickable to sort

**Comment by midigofrank** [comment]
Hey @taylordowns2000 , I'll work to make the whole header clickable.

I however left out only showing the icon on hover intentionally because it might be confusing to the user. 

The table has 5 columns:
- Column 1 (Name) shows a sort icon by default
- Columns 2-4 have no indication of sortability
- Column 5 (Last Activity) requires hovering to reveal its sortable nature

This inconsistent approach could make it unclear which columns users can actually sort. The Tailwind table example you've highlighted makes a lot of sense because all its columns have a consistent sortability indicator.

If we're not showing the icon by default, how will they know that **Last Activity** is sortable?

Let me know what you think

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
this looks great from a UI perspective, but i'm worried that the `sortable_table_header` is in "dashboard_live" — shouldn't this live somewhere else if it's the way that every table in the app will be sorted?

**Comment by midigofrank** [comment]
Good point @taylordowns2000. I've made it into a global component

**Review by stuartc — APPROVED** [review]

**Pull request merged**
