### PR TITLE
change 'schema' to 'type'

### PR DESCRIPTION
**Pull request by avinashdhauni**

### CODE REVIEW

**Comment by taylordowns2000** [comment]
this closes #260

**Comment by taylordowns2000** [comment]
This is great, @avinashdhauni . Thanks so much.

**Comment by avinashdhauni** [comment]
My pleasure. It was amazing contributing to the project. I am at a
beginning stage of programming and i didn't knew how to contribute to the
open source because the codes are so big and i wasnt able to understand.
But something like this was easy enough for me to complete. So I am
very grateful to you for this opportunity.

**Comment by taylordowns2000** [comment]
Great to hear it, @avinashdhauni . What do you think of https://elixir-lang.org/ and https://www.phoenixframework.org/ ? Have you worked with these technologies before?

If you're up for it, I know that @amberrignell , the product manager for Lightning, would love to speak with you next week to hear how you discovered OpenFn, what it was like to get the project set up, and gather any feedback you might have on the application (or even on [OpenFn.org](https://www.openfn.org))

**Comment by stuartc** [comment]
@avinashdhauni fyi I've changed the form a bit, since the column name is `schema` - when changing the html test for a label, it should be done in a block.

By changing the field name, the `for` attribute would also be changed to `for="credential-form_type"`, which breaks the browser behavior when clicking on a label and it selecting the associated input. Thanks for the PR!

See: https://github.com/OpenFn/Lightning/commit/acb7336d850c1ee03089bda5e509dce84adea5fa

**Pull request merged**
