### PR TITLE
Highlight adjacent edges in the Workflow Diagram

### LINKED ISSUE #2358: Workflow Diagram: when selecting (or hovering?) a node, highlight the connected edges
On the more complicated workflows, it can be hard to tell where paths are actually heading to - especially when, as they tend to do, the paths cross over each other and behind other nodes.

It can also be hard to tell which paths belong to a given node.

It would be very useful, when hovering over a node or when selecting one, to highlight all connected edges.

### PR DESCRIPTION
**Pull request by josephjclark**
### Description

This PR makes large workflow diagrams a little easier to read by highlighting edges connected to the selected node.

It's particularly useful when edges are drawn behind nodes, making it hard to read connections.

Closes #2358

image

### Validation steps

1. Open up your favourite workflow
2. Select a node. Adjacent edges should highlighted
3. Select an edge. Only the edge should be highlighted (do you think we should highlight the nodes too? I think the edge i quite legible)

### Notes

This PR is branched off of `canvas-test-harness`.

### Pre-submission checklist

- [ ] I have performed a **self-review** of my code.
- [ ] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [ ] I have updated the **changelog**.

### CODE REVIEW

**Review by christad92 — APPROVED** [review]
Thanks.

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
Looks like the adaptor icons no longer show on this branch. Same problem for anyone else?

**Comment by josephjclark** [comment]
Ah that might be me in #2376 - let me take a look

**Comment by josephjclark** [comment]
Yep, that's fixed on the underlying branch :+1:

**Review by stuartc — APPROVED** [review]

**Pull request merged**
