### PR TITLE
Workflow diagram

### LINKED ISSUE #449: Specify timezone on the runs history
**Describe the bug** A clear and concise description of what the bug is.
Currently the user has no way of knowing what timezone a 'last run' is in.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to
happen.
Display the timezone in parentheses next to the 'Last run' column header

**Screenshots** If applicable, add screenshots to help explain your problem.

**Additional context** Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by taylordowns2000**
## Any notes for the reviewer ?

1. tests with `ava` are not running yet — they complain about using import outside a module
2. do we need `rimraf` and build stuff? everything appears to be working exactly as desired in my browser testing without brining over any of those devDependencies or build tools: https://github.com/OpenFn/kit/blob/main/packages/workflow-diagram/package.json#L25-L44
3. is there anything else we want to bring from kit? (how about examples? is that taken care of by "demo seeds" in lightning? i think yes.)
4. this PR will drop workflow-diagram from kit: https://github.com/OpenFn/kit/pull/119

## Related issue

For # 485

Closes #449 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [x] If needed, I've updated the changelog
- [ ] Amber has QA'd this feature

### CODE REVIEW

**Comment by josephjclark** [comment]
1. I can fix ava for you, if we think it's worth keeping the tests.
2. Yeah, you're right, the rollup build stuff should all be redundant now
3. There are arguments in favour of keeping examples. It can be nice to test the components standalone, without all the Lightning overhead. But it's probably not worth the overhead.

This is one for Stu really but the src folder in `workflow-diagram` bothers me. And the interface between lightning-hook and actual component is getting sketchier. You've got lightning-side stuff a the top and react-side stuff in src. Still not quite sure the best way to organise this.

**Comment by taylordowns2000** [comment]
Thanks Joe! Added @stuartc as a reviewer for his thoughts on src and examples!

**Comment by josephjclark** [comment]
I've sorted ava but it's not currently hooked up to CI. I'm not sure if we want to at this stage?

**Comment by taylordowns2000** [comment]
this also closes #449

**Pull request merged**
