### PR TITLE
Refactor Manual Run Component

### LINKED ISSUE #959: Change Run button to be Save + Run
**Problem:**
The Run button in the Job Editor, currently only runs the job in it's last saved state - so it's easy for a user to edit the job body and click Run only to find that their changes **aren't** reflecting.

You _can_ work with thing by clicking Save at the bottom right and/or using the Ctrl/Cmd+S keyboard shortcut; this isn't particularly obvious though.

Saving is currently bound to the entire workflow, so in order to save a job the workflow must be valid.

**Solution:**
Change the _Run_ button to save the job and then run the job.
Update the button wording to reflect the fact it saves as "Save & Run".

**Notes:**
- When the workflow changeset is invalid, the button must be disabled.
- When the manual run chageset is invalid, the button is also disabled. (Existing behaviour)

### LINKED ISSUE #1026: Move "Save & Run" button to bottom right
Right now, the "Save & Run" button is at the bottom of the input panel but we'd like it by the "Save" button:
image

Down here:
image

Notes:
1. Control-S (or Command-S) should still work to save the job no matter what panel is focussed on this page.
2. Control-Enter (or Command-Enter) should still work to save and run the job no matter what panel is focussed.
3. The button should still be greyed out if no input is provided.

### PR DESCRIPTION
**Pull request by stuartc**
## Notes for the reviewer

This comes off the back of the complexities around adding "Save and Run" for manual runs.

This is a _large_ refactor, with the Workflow.Edit LiveView getting a little bigger - but several other modules being significantly reduced in size.

Notably the `ManualRunComponent` doesn't exist anymore, it is now a function component under `lib/lightning_web/live/workflow_live/manual_workorder.ex`.

Other notable changes include:

- The introduction of Phoenix 1.7 style form/input components, they are located in `new_inputs.ex` for now, we will need to test for compatibility (and/or deprecate our existing `Form` module components) with importing them into our `LightningWeb.CoreComponents` module.
- Added `Repo.transact/2`, a useful wrapper around `Repo.transaction/2` that works nicely with `with` statements.

## Still to do

- [x] Fix tests, awaiting on #966 .

## Related issue

Fixes #959
Fixes #1026

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

**Comment by stuartc** [comment]
@elias-ba @taylordowns2000 I've marked this as draft for now, as there are a handful of tests I need to fix, but I'm waiting for #966 to be completed and will touch them up then.

But this is ready for testing locally.

Sorry about the massive PR, I have added Heroicons using the approach that Phoenix 1.7 uses - so there is a fat commit with 100+ SVG files.

**Comment by stuartc** [comment]
Ergh, I see some layout regression here.

image

@taylordowns2000 do you know anything about these z-index style layout changes?

**Comment by stuartc** [comment]
@taylordowns2000 fixed the UI regression here: https://github.com/OpenFn/Lightning/pull/1066/commits/d58e91de36e42f97165ed43e1f90fb001541c23e

But in order to not make this a crazy drawn out solution, we can no longer see the box shadow between the top bar and the workflow editor.

The z-index that was there always won because the top bar is higher than the 'inner content', even though the modals etc were highest; but only in the context of the 'inner content'.

**Comment by josephjclark** [comment]
@stuartc thanks for the shoutout.

Funnily enough I touched some z-index stuff in the editor modal this week: https://github.com/OpenFn/Lightning/pull/1065/commits/718ce6cf34a2ae22bd4028a60c8e01c526a874ac

These things must all be related.

**Pull request merged**
