### PR TITLE
Enhance AI Assistant's UI ✨ 

### PR DESCRIPTION
**Pull request by elias-ba**
### Description

This PR brings few changes that enhances the look and feel of the AI assistant panel. Those changes include the sessions list, the chat input, and the chat messages. The AI assistant still works as before. These are just esthetics !

Re #2497 

### Validation steps

1. Open the AI assistant panel
2. Note the changes in the chat input UI
3. Check that it still works as before including the tab key to indent and the cmd/ctrl + enter keybinding to send a message
4. Type your prompt to start a new chat session
5. In the chat session, note the little UI enhancements in the chat bubbles, the user and assistant avatars, and the global look and feel
6. Close the chat session and create many other sessions
7. Go back to the chat sessions list
8. Note that you can now sort the sessions items in the list by date 

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

**Comment by josephjclark** [comment]
@elias-ba I think this looks absolutely fantastic - excellent work again!

I'm going to open a branch with a couple of tiny tweaks

Is it possible that when the Chat History is open, the placeholder can say "Start a new chat", but when a chat is open, it says "Ask another question"? Because at the moment the placeholder is a bit misleading (well, actually, it's straight up wrong)

I think we need to split syntax highlighting out into a new issue. It's a great idea, but the styling is inconsistent. At the moment the assistant's code looks like this:

image

But Adaptor docs code boxes look like this:

image

And our actual code looks like this:

image

And on the docs site our code looks like this:

image

Ok, so we don't need to make all the code look exactly the same - but ideally within lightning we should have a standard way of rendering/highlightning code, otherwise it's just madness.

So actually I'm going to copy this out into a new ticket

**Comment by josephjclark** [comment]
Oh, also, while we're at it, the session name is way behind the standard of everything else now: 
image

**Comment by josephjclark** [comment]
@elias-ba Oh one more suggestion: Instead of "Sort by Date", can you make the label "Latest" if you're showing the newest first, or "Oldest" if you're showing the oldest first

**Comment by elias-ba** [comment]
Hey @josephjclark thanks for the review here. This is great. I will revert the syntax highlighting commit and we hold it until later. I will look at the other change requests and work on them now.

**Comment by elias-ba** [comment]
Hey @josephjclark this is ready for you to have another look. Thanks

**Review by josephjclark — APPROVED** [review]
Great stuff @elias-ba !

**Review by stuartc — APPROVED** [review]

**Comment by stuartc** [comment]
@elias-ba can you make an issue for the syntax highlighting please, its going to be a great addition - just need to get it bundled into the apps js instead of using a CDN.

**Pull request merged**
