### PR TITLE
Hide deprecated adaptors from version picklist

### LINKED ISSUE #2169: Filtering deprecated adaptors from dropdown list
**Description:**

The current dropdown list for selecting adaptors includes both active and deprecated options. This can be confusing for users and lead to selecting unsupported adaptors. 

**Proposed Solution:**

Implement a filtering mechanism to exclude deprecated adaptors from the dropdown list. 

**Additional Considerations:**

* If there's a need to retain visibility of deprecated adaptors for informative purposes, consider a separate option to "Show Deprecated Adaptors". This would allow users to view all options but clearly differentiate between active and deprecated choices.
* Provide a clear indication to the user if a selected adaptor is deprecated. This can be done through a visual cue (e.g., dimmed text) or a tooltip message.

**Benefits:**

* Improved user experience by presenting a clear and concise list of supported adaptors.
* Reduced risk of users selecting deprecated and potentially unsupported adaptors.

### PR DESCRIPTION
**Pull request by taylordowns2000**
Fixes #2169 

## Validation Steps

- notice `language-salesforce@4.4.0` and `@5.0.1` in your adpator list on `main`.
- clear your local adaptor cache: `rm -rf /tmp/openfn/worker/repo`.
- switch to this branhc
- boot up lightning
- notice that `4.4.0` and `5.0.1` no longer appear

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

### CODE REVIEW

**Review by mtuchi — COMMENTED** [review]
@taylordowns2000 Tested locally everything seems fine ✅ , 
But i think it would be nice if we can have unit test in `test/lightning/adaptor_registry_test.exs`.  Do you think we should have a test like this 👇🏽 ? 
```
test"filter deprecated adaptors from the adaptor lists" do ...
  //assert deprecated version of an adaptor will be filtered 

end
```

**Comment by taylordowns2000** [comment]
> @taylordowns2000 Tested locally everything seems fine ✅ , But i think it would be nice if we can have unit test in `test/lightning/adaptor_registry_test.exs`. Do you think we should have a test like this 👇🏽 ?
> 
> ```
> test"filter deprecated adaptors from the adaptor lists" do ...
>   //assert deprecated version of an adaptor will be filtered 
> 
> end
> ```

i took a look, but as far as i can tell we don't have any tests for the response processing from NPM. an additional set of tests (including the one you suggest) is a _great_ idea and we should do it in https://github.com/OpenFn/lightning/issues/2172

**Comment by stuartc** [comment]
> > @taylordowns2000 Tested locally everything seems fine ✅ , But i think it would be nice if we can have unit test in `test/lightning/adaptor_registry_test.exs`. Do you think we should have a test like this 👇🏽 ?
> > ```
> > test"filter deprecated adaptors from the adaptor lists" do ...
> >   //assert deprecated version of an adaptor will be filtered 
> > 
> > end
> > ```
> 
> i took a look, but as far as i can tell we don't have any tests for the response processing from NPM. an additional set of tests (including the one you suggest) is a _great_ idea and we should do it in #2172

We have tests that the registry requests all modules, and then a small test that language-common is queried, for which we provide a stubbed response in a fixture... So we have the bits to test this - but it's better tested more thoroughly; happy to move the testing out to a bit later. But @mtuchi is right, we definitely must test this.

**Comment by taylordowns2000** [comment]
All makes sense. I've linked these comments to the new issue. Thank you both!!!!

**Pull request merged**
