### PR TITLE
Increase history search query timeout

### LINKED ISSUE #1461: DBConnection.ConnectionError: tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the...
Sentry Issue: [LIGHTNING-81](https://openfn.sentry.io/issues/4665552286/?referrer=github_integration)

```
DBConnection.ConnectionError: tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
  File "lib/ecto/adapters/sql.ex", line 1047, in Ecto.Adapters.SQL.raise_sql_call_error/1
  File "lib/ecto/adapters/sql.ex", line 945, in Ecto.Adapters.SQL.execute/6
  File "lib/ecto/repo/queryable.ex", line 229, in Ecto.Repo.Queryable.execute/4
  File "lib/ecto/repo/queryable.ex", line 19, in Ecto.Repo.Queryable.all/3
  File "lib/ecto/repo/queryable.ex", line 151, in Ecto.Repo.Queryable.one/3
...
(3 additional frame(s) were not displayed)

(DBConnection.ConnectionError tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated))
```

### PR DESCRIPTION
**Pull request by jyeshe**
## Notes for the reviewer

Use a customized version of [scrivener_ecto](https://github.com/drewolson/scrivener_ecto) to set workorder query timeout that is found here: https://github.com/drewolson/scrivener_ecto/compare/master...OpenFn:scrivener_ecto:timeout_opts

## Related issue

Fixes #1461 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
two quick ones @jyeshe -
1. does this fix https://github.com/OpenFn/Lightning/issues/1491 ?
2. the changelog looks off. your change should go in the unreleased section at the top and follow the convention up there: https://github.com/OpenFn/Lightning/pull/1490/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR9-R17

**Comment by jyeshe** [comment]
> two quick ones @jyeshe -
> 
> 1. does this fix [Fix flaky "lifecycle of an attempt" test #1491](https://github.com/OpenFn/Lightning/issues/1491) ?
> 2. the changelog looks off. your change should go in the unreleased section at the top and follow the convention up there: https://github.com/OpenFn/Lightning/pull/1490/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR9-R17

It helps but still getting the flaky "lifecycle of an attempt".
Thanks for noticing the changelog.

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
Great! Please put a link to the issue this closes in the changelog entry and then I think you're good to go. See required format here:
image

**Review by stuartc — APPROVED** [review]
👌

**Review by taylordowns2000 — APPROVED** [review]

**Pull request merged**
