### PR TITLE
Test Harness for Layouts

### LINKED ISSUE #2366: Edges/paths tend to overlap on the canvas
As the workflow in a canvas grows with more edges and paths, we have situations where edges and paths overlap as shown in the video below. 

https://www.loom.com/share/cbd61186553a482e86b8cc4e6dd59cf7?sid=216dfec4-4065-4c8a-9499-1c18a976c869

There are two potential ways we can do this: 
1. Have a collision detection for paths and edges and use that to ensure they don't overlap. 
2. Allow users to manually arrange edges on the canvas. This way, we can store the x/y positions of each edge.

### PR DESCRIPTION
**Pull request by josephjclark**
### Description

This PR creates a test harness for workflow layouts. It'll run a bunch of workflows and save screenshots of them to disk.

The idea is that I can make changes to the layout and run it against many workflows at once, so we can easily compare changes.

* Restore the old dev-server (which makes it easier to dev this stuff)
* Add repro cases to the dev server
* Set up a puppeteer script which will capture a screenshot for every chart.

Works great!

I've also added a bunch of little fixes to the dev server and some util functions to get it all working again. There are a couple of diffs against production code, but only very very minor

Here's a grid of screenshots I took.

image

## How to run

```
npm run test:workflow-snapshots
```

To get this to work I had to install chromium specially and pass the path to the bin. This should be looked at more but it's likely to only be me running this stuff, so I'm not too worried.

### Pre-submission checklist

- [ ] I have performed a **self-review** of my code.
- [ ] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [ ] I have updated the **changelog**.

### CODE REVIEW

**Comment by josephjclark** [comment]
Hey @stuartc would you mind merging this end?

It's just test code. Doesn't affect anything in prod. Thanks!

**Comment by josephjclark** [comment]
hey @stuartc can you take a quick look at this and merge it down? Very low risk, just some dev tooling I'd like to keep.

**Comment by josephjclark** [comment]
This branch may have broken adaptor icons

**Comment by josephjclark** [comment]
@stuartc This all looks good now :+1:

**Review by stuartc — APPROVED** [review]

**Pull request merged**
