### PR TITLE
Updating erlang image tag in Dockerfile-dev

### PR DESCRIPTION
**Pull request by piische-tph**
The current tag is not working

## Related issue

Fixes #

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

**Comment by stuartc** [comment]
@piische-tph thanks for this, you're right - the bullseye image isn't available anymore.

This dev dockerfile has fallen out of date, the main `Dockerfile` uses a bookworm image.

Instead of changing the Elixir version as well, could you try the bookworm image used in `Dockerfile`? See: f87434c1d27ef1defa24f1e888dcfcc76c1d35ba

I'd like to know your success using this image (once the image/versions are correct), it's been a while since I used it so if more needs to be done to it - we can plan some further work on it.

**Comment by piische** [comment]
Hey @stuartc,
Thanks, I tried with the  bookworm image and this also worked to get the docker running.

I was able to run all commands and the compose up also worked, I have to wait for our server admin to open a port for the postgres before I have everything settled and can test it, but the setup so far worked perfectly fine.

Best regards,
Patrick

**Comment by stuartc** [comment]
@piische-tph if you could update the `Dockerfile-dev` to use the bookworm image and drop the change to the Elixir version (since the production image uses 1.15.4 it's best to keep the two aligned) I'd be happy to merge that change.

**Comment by stuartc** [comment]
Thanks @piische-tph!

**Pull request merged**
