### PR TITLE
Lay down authorization across entire app

### LINKED ISSUE #645: Lay down authorization across entire app
### User story
As a lightning administrator, I would like authorization to be implemented for every key action carried out in Lightning, so that I can be sure that only those granted explicit access can view or edit important resources.

### Details
The pattern for authorization has already been laid out in [this PR](https://github.com/OpenFn/Lightning/pull/613/files). 

Using the pattern above, add authorization to the actions detailed in [this doc](https://docs.google.com/spreadsheets/d/1mlWjlvVdhupI3Ph0msf9nE2K7Uoe-qklOj81cG0N19c/edit#gid=547880405)

### Release notes
- [ ] Authorization for Lightning superusers and users, and project roles viewer/editor/admin/owner. See [link to test file] for more details. 

### User acceptance criteria
- [ ] The tests clearly communicate which actions different users can and cannot perform in Lightning. 
- [ ] These permissions are in line with the doc provided above.

### PR DESCRIPTION
**Pull request by elias-ba**
## Implementation Plan

- [x] Follow the actions and rules defined in [this spreadsheet](https://docs.google.com/spreadsheets/d/1mlWjlvVdhupI3Ph0msf9nE2K7Uoe-qklOj81cG0N19c/edit#gid=547880405) and create the associated Bodyguard policy functions in the `lib/lightning/policies/users.ex` or `lib/lightning/policies/project_users.ex` modules.
- [x] Test the `Lightning.Policies.Permissions.can/4`

Implemented authorizations
- [x] Admin settings
- [x] Profile and credentials page
- [x] Workflows
- [x] History
- [x] Project settings

## Related issue

Re #645 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If needed, I've updated the changelog
- [ ] Amber has QA'd this feature

### CODE REVIEW

**Review by taylordowns2000 — COMMENTED** [review]
@elias-ba , I need a closer look in the morning but to start:
1. It looks clean. Nice job!
2. Your use of "refute" with "another user" seems redundant. The whole point of that ":thief" block is to show that other users cannot perform actions on project resources that they're not members of.

**Comment by elias-ba** [comment]
> @elias-ba , I need a closer look in the morning but to start:
> 1. It looks clean. Nice job!
> 2. Your use of "refute" with "another user" seems redundant. The whole point of that ":thief" block is to show that other users cannot perform actions on project resources that they're not members of. 

Morning @taylordowns2000 

1. Thanks ❤️ 
2. Another user represents any user different than the current logged in user. Some feature like editing digest or failure alerts can only be performed by the logged in user on their own records. So the `authorize` function takes the current user and the user we are checking for the authorization.

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
@elias-ba , the superuser permissions don't look quite right. please double each permission with the row in the spreadsheet. thank you!

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
@elias-ba , thanks for the productive call today! Please _implement_ these new actions in the various `live_views` or `controllers` as demonstrated for `:edit_job` — shown in the link "use this pattern" on the original issue.

**Review by stuartc — COMMENTED** [review]
@elias-ba all good here, this is a great start.

As we discussed, please change the commit with at-mention.
Rebase and fix the merge conflict on CHANGELOG,
Remove the "fixes" prefix on the PR description and point me at the subsequent draft PR for the application behaviour changes.

I'll merge as soon as that's done. :+1:

**Comment by elias-ba** [comment]
@stuartc thanks, I did rebase and squash. Edited the description to change fixes to related. And here is the new draft PR for the remaining work: https://github.com/OpenFn/Lightning/pull/667

**Pull request merged**
