### PR TITLE
Port demo runs from main to nodes and edges branch

### LINKED ISSUE #879: Change SetupUtils to create an edges workflow
Change SetupUtils to create an edges workflow.

It's one of the places that uses `.trigger`, but worth mentioning as it's own thing.

This affects the UserRegistrationController when they sign up (edited)

### PR DESCRIPTION
**Pull request by elias-ba**
## Related issue

Fixes #879 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Amber has **QA'd** this feature

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
Hey @elias-ba , thanks for this! Please see slack for a couple of thoughts on the review process. The things related to this code I can see are:

1. I don't think there should be an entry in the changelog.
2. If there is new functionality delivered by these scripts, we probably also want extensions to the tests which confirm that the new functionality is in place.

I know that this isn't code used by the main application--it's a setup helper--but I think we still have some tests to ensure that the setup scripts do what we think they do.

**Comment by elias-ba** [comment]
@taylordowns2000 I have added tests and handled you change requests. Please can you re-review and let me know. cc @amberrignell whenever you available this is ready for QA.

**Review by amberrignell — APPROVED** [review]

**Comment by taylordowns2000** [comment]
@elias-ba , please rebase this again on `nodes-and-edges-release` and re-confirm that everything works as expected via the tests and click tests. (apologies from @stuartc , once you do this he'll merge it in.)

**Comment by elias-ba** [comment]
Closing in favor of #948

**Pull request closed without merging**
