### PR TITLE
AI Assistant UI tweaks

### LINKED ISSUE #2409: AI assistant: when a new response comes in, scroll to it
Using the AI assist, if I have a few messages, then text can scroll out of the main screen.

If I scroll up the chat to an earlier message, then type a question and send it, the NEW response will come in out of view. It'll come in at the bottom of this history div, out of sight.

Basically we should probably call `el.scrollIntoView()` when a new response is received.

### LINKED ISSUE #2477: AI Assistant: Layout problems with scrollbar
The internal layout of the AI assistant isn't right. The scrollabar is in the wrong place and there's strange internal padding

image

### LINKED ISSUE #2481: AI Assistant: Disclaimer should be shown once per user per day
**Acceptance critiria:**

* Disclaimer should be shown once per user per day
* Add a random quote from [this list](https://docs.google.com/document/d/1DesHrt19loIaNWQGbYfjpBu3zi_JorxDSW6ahKaAZus/edit?tab=t.0), nicely formatted

**Discussion:**

The AI assistant disclaimer panel is designed to add very lightweight friction to users coming into the AI assistant. It's designed to make users think twice about using AI and put a little bit of onus back on the human.

In main right now, the disclaimer is only every shown once per user. It'll be forgotten within a minute of closing, and never seen again. There is literally no benefit to it.

The recommendation as per #2411 was to restore the disclaimer once per user, per project, per day. As in - every day, when a user opens the assistant on project for the first time that day, the disclaimer appears.

I actually think per project is unnecessary, but I'd really like to see the disclaimer splash be shown once per day per user.

It's OK to check on page load whether to show the disclaimer. We don't need a timer in the page or anything to do it in the session. It doesn't need to be ironclad or foolproof.

I would actually write the marker to local storage, not the database. If the user logs in on two browsers, they'll have to dismiss the disclaimer twice. This really isn't a big deal.

### LINKED ISSUE #2493: AI Assistant: Wrap content in chat  interface.
We should be wrapping the content of the chat interface based on the width of the panel. We don't users be scrolling left and right to see the content.

image

### PR DESCRIPTION
**Pull request by midigofrank**
### Description

This PR makes a couple of UI tweaks to the AI Assistant. Most notably, it makes the disclaimer appear once every day.

Closes #2481 
Closes #2477
Closes #2409
Closes  #2493

### Additional notes for the reviewer

The control flag for the disclaimer is tracked in the database as a user preference with a timestamp value

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

**Comment by midigofrank** [comment]
Working on using timestamp as the flag. This eliminates the need for an Oban job

**Comment by josephjclark** [comment]
Vertical scrolling is fantastic!

Disclaimer and quotes is merged!

I'm struggling with horizontal scrolling on the code boxes though. We have it working great in the [docsite](https://docs.openfn.org/adaptors/packages/collections-docs#collections_each) - I just can't see what the difference is in styles. We just need the `pre` tag to a) not line break but b)  show a scrollbar and not extend its parent.

There must be some parent styling interfering - I'll dig a bit deeper and see if I can find it

**Comment by josephjclark** [comment]
Aha - if I take the parenting flexbox away, it wraps properly (and the docsite does not use flexbox) 
image

**Comment by midigofrank** [comment]
Interesting

**Review by stuartc — APPROVED** [review]

**Review by josephjclark — APPROVED** [review]

**Pull request merged**
