### PR TITLE
149 settings page liveview

### PR DESCRIPTION
**Pull request by NickGowdy**
These code changes are to convert the `/profile` part of the website into Liveview. 

See below for following changes:

- Created profile liveview with form component for editing profile password and email.
- Unit tests to assert liveview behaviour.

`UserSettingsController` and all associated code to be removed in separate PR to fix saving profile email using token.

### CODE REVIEW

**Comment by taylordowns2000** [comment]
@NickGowdy , I know that this is a work in progress, but I just had a chat with @stuartc and we wanted to give you some early feedback to help shape the journey 😄 . (Apologies in advance if you already know this stuff and just haven't got there yet.)

## Notes

1. Thank you! So excited to see this coming together.
2. You’ve done the whole thing in `edit.html.heex` rather than having an `edit.html.heex` and a `form_component.html.eex` - since this is a pretty straightforward form and it’s not going to be used by multiple live views I think that’s OK... maybe even better.
3. We’ve got some “pre-flight checks” that we run on each PR before they can be merged. when you’re happy with the functionality and have added a few tests, try running the checks defined in the [circleCI config](https://github.com/OpenFn/Lightning/blob/main/.circleci/config.yml#L69-L96) to make sure you’re formatted properly, etc.
4. I'm not sure if the `on_mount {LightningWeb.Hooks, :project_scope}` call on ProfileLive is necessary, as the route doesn't have a `:project_id` in it.
5. I don't see any behaviour for handling saving. So we need to get that in there before we can replace the existing implementation.
6. The **email** related stuff in `user_controller.ex` is tricky — some of these actions are assumed to be coming in with a token and not an existing session.

On number 6, it seems like this was more than you bargained for in the initial issue. (This isn't, as it turns out, _just_ a form that saves stuff.) We'd be totally OK breaking that other email notification/password reset stuff into another issue, but would want to slice it out and document it carefully if you don't want to work through it for this one.

What do you think? Happy to respond to your desired level of complexity here!

**Comment by NickGowdy** [comment]
Hey @taylordowns2000,

Thanks for the feedback, it's really helpful. I thought I should get a draft PR out early so my progress is a bit more visible and the team can give me some advice.

I think understand all your points, I reckon there is enough there for me to do the remaining changes and get everything ready for review.

**Comment by NickGowdy** [comment]
Hey again @taylordowns2000,

I'm trying to re-implement the save password functionality, but it doesn't seem to hit the function. Is there something obvious I'm missing in my latest commit?

**Comment by NickGowdy** [comment]
Hey @taylordowns2000 

I think the code is close to being ready for review. Only a few small changes remaining:

- Finish the unit tests, some tips on how to do this would be helpful.
- Some code is commented out (`UserSettingsController`), should I remove this or keep it in there for now? I need to implement the token functionality for saving profile email (Separate PR). 
- Not sure if the pattern matching can be improved in `LightningWeb.ProfileLive.FormComponent` for `handle_event`.

Thanks for your help
Nick

**Comment by stuartc** [comment]
Hey @NickGowdy! This is coming along nicely!

1. For testing there are a few examples for forms in the code base, I would suggest looking at `job_live_test.exs` or `first_setup_live_test.exs`; although the Job form has other stuff (live a fancy-pants virtual field dropdown) that you can ignore, the basic flow is:
  - Render a liveview with a given url
  - Apply some params to a form (in the case of Profile there is more than one, so individual cases will need to be done for each)
  - Test that a the HTML rendered reflects the change you expect.
```elixir
assert form_live
       |> form("#job-form", job: @invalid_attrs)
       |> render_change() =~ "can&#39;t be blank"
```
  - Then test the behaviour when the form is submitted, like does it direct and what would the other page show as evidence there was a redirect.

We've found liveview testing quite difficult to get comfortable with, especially with experience from different frameworks - the important thing to remember, is that you're testing the LiveView and it's components; so things like clicks aren't real clicks but messages passed to the LiveView process. It may seem obvious in hindsight but I got tripped up a bunch of times with my brain telling me to treat it like a browser test.

2. As for the `UserSettingsController`, I think we can delete it for now - since we want to get these changes merged into main as soon as it's ready; obviously we don't want to throw it away - in the spirit of moving step by step we can pull the parts of the previous implementation out of git for the next step.

3. Regarding improving the pattern matches, I would keep just changeset structs in the assigns and remove the `id` key.  
  You can get the users id from the changesets using `Ecto.Changeset.get_data(changeset, :id)`, we don't want to add a users id  in a hidden field  as that would allow someone to potentially change another users password.  
  Also since the changeset _is_ the user, you already have the `User` struct - no need to fetch it again.
  Removing ignored matches like `_current_password` will clean up the interface a bit, my view is that while guarding against bad params if we're not using the keys (and we have tests) I don't think we're losing anything.
  
Sorry I know this is massive comment, I hope it helps - but if it doesn't please feel free to ask more questions! Thanks for your contribution so far!

**Comment by NickGowdy** [comment]
Hey @stuartc 

Thanks for the tips, I've managed to tidy up the validation functions for `form_component.ex` in profile. However every time I tab out of a textbox it clears all of them.

```
@impl true
  def handle_event("validate_password", %{"user" => user_params}, socket) do
    changeset =
      socket.assigns.user
      |> Accounts.change_user_password(user_params)
      |> Map.put(:action, :validate_password)

     {:noreply, assign(socket, :password_changeset, changeset)}
  end

  @impl true
  def handle_event("validate_email", %{"user" => user_params}, socket) do
    changeset =
      socket.assigns.user
      |> Accounts.change_user_email(user_params)
      |> Map.put(:action, :validate_email)

     {:noreply, assign(socket, :email_changeset, changeset)}
  end
```

Can you see what I could be missing in the above functions? I would expect the textbox value to still be there and it to display a validation error message on the UI. For example if I type a password with too few characters.

**Comment by NickGowdy** [comment]
I fixed my password issue in the end using this link: [https://github.com/phoenixframework/phoenix_live_view/issues/70](https://github.com/phoenixframework/phoenix_live_view/issues/70)

and doing this:

` value: input_value(f, :current_password),`

**Comment by taylordowns2000** [comment]
hey @NickGowdy , ack, sorry about this... not a bug per se, but a feature change: currently, when the password is changed the session is getting invalidated so `Accounts.get_user_by_session_token(session["user_token"])` in `init_assings.ex` returns `nil`. (Hence your `nil.role` error.)

I just had a quick chat with the team and we don't like that behaviour... you should be able to stay logged in if you've confirmed your password but all other sessions should be destroyed. If you agree, please **make the following change** to the form component which creates a new session (after deleting all the old ones in) and redirecting the user to the home screen.

```ex
diff --git a/lib/lightning_web/live/profile_live/form_component.ex b/lib/lightning_web/live/profile_live/form_component.ex
index 36cb44c..1c71948 100644
--- a/lib/lightning_web/live/profile_live/form_component.ex
+++ b/lib/lightning_web/live/profile_live/form_component.ex
@@ -26,11 +26,18 @@ defmodule LightningWeb.ProfileLive.FormComponent do
            current_password,
            user_params
          ) do
-      {:ok, _user} ->
+      {:ok, user} ->
         {:noreply,
          socket
          |> put_flash(:info, "Profile password updated successfully")
-         |> push_redirect(to: socket.assigns.return_to)}
+         |> redirect(
+           to:
+             Routes.user_session_path(
+               socket,
+               :exchange_token,
+               Accounts.generate_auth_token(user) |> Base.url_encode64()
+             )
+         )}
```

For what it's worth, the code that destroys all those tokens in the first place is over in the accounts context:

```
    |> Ecto.Multi.delete_all(
      :tokens,
      UserToken.user_and_contexts_query(user, :all)
    )
```

that should clean up the happy paths. I'll open a different issue that handles the case when `Accounts.get_user_by_session_token` more, erm, elegantly! it should redirect to `/login` with some sort of `nextPage={whereYouJustCameFrom}` param instead of blowing up!

## to finish up this PR

can you make sure the other tests are passing (`mix test`) and that you've run `mix format` and `MIX_ENV=test mix dialyzer --plt`. (see circle output [**here**](https://app.circleci.com/pipelines/github/OpenFn/Lightning?branch=pull%2F218%2Fhead).)

thanks so much!

**Comment by NickGowdy** [comment]
Hey @taylordowns2000 

I've implemented your suggestion so the user doesn't get logged out. The ` |> put_flash(:info, "Profile email updated successfully")` doesn't appear on the screen, I'm assuming because we navigate to a different page.

We have no failing user tests because `user_setttings_controller.ex` is commented out. Are you happy for me to delete `user_setttings_controller.ex` and it's tests as we've converted it into liveview?

**Comment by NickGowdy** [comment]
In `profile_live_tests.exs` does anyone know what to write for this:

```
 {:ok, _, html} =
        profile_live
        |> form("#password_form", user: @update_password_attrs)
        |> render_submit()
        |> follow_redirect(conn, Routes.user_session_path(conn, :new))
```
I'm not sure how to do the assertion here.

**Comment by taylordowns2000** [comment]
@NickGowdy , wow... tremendous stuff here!

Yes... when you `follow_redirect` there you're getting back a new live view. See the pattern [here](https://github.com/OpenFn/Lightning/blob/main/test/lightning_web/live/credential_live_test.exs#L45-L52) (where following a redirect from `index_live` returns `edit_live`).

To make sure the redirect to the workflows page works and your user gets their new session created, i'd do something like this:

```ex
{:ok, workflow_diagram_live, html} =
        profile_live
        |> form("#password_form", user: @update_password_attrs)
        |> render_submit()
        |> follow_redirect(conn, Routes.user_session_path(conn, :new))

assert_redirected profile_live, Routes.user_session_path(conn, :new)

assert has_element?(workflow_diagram_live, "SOME ELEMENT TO SEARCH FOR")
## or
assert html =~ "Some text you expect to see on the screen"



```

**Comment by NickGowdy** [comment]
Hey @taylordowns2000 

I've tried your suggestion and I'm getting an error: 
```
  test/lightning_web/live/profile_live_test.exs:42
     ** (RuntimeError) LiveView did not redirect
     code: |> follow_redirect(conn)
     stacktrace:
       test/lightning_web/live/profile_live_test.exs:62: (test)
```
I'm a bit stuck now as I've tested the functionality manually and it works but the test returns that error. Could it be possibly my test data is wrong for the happy paht?

**Comment by NickGowdy** [comment]
The problem with the unit test was the test data wasn't setup correctly but now it's saying the assertion is incorrect:

```
 test/lightning_web/live/profile_live_test.exs:42
     ** (ArgumentError) expected LiveView to redirect to "/users/log_in", but got "/users/token_exchange/wGML4U85dMXq6ZncOo9Lhus037usVdkvFsxInxDRKPM%3D"
     code: |> follow_redirect(conn, Routes.user_session_path(conn, :new))
     stacktrace:
       (phoenix_live_view 0.17.11) lib/phoenix_live_view/test/live_view_test.ex:1548: Phoenix.LiveViewTest.__follow_redirect__/4
       test/lightning_web/live/profile_live_test.exs:62: (test)
```

This makes sense because the redirect is to the url for `exhange_token`. However I don't know how to do this assertion correctly without the token.

**Comment by NickGowdy** [comment]
I ended up fixing my unit test in the end by using a similar assertion as used in `first_setup_live_test.exs`.

Also I believe I've fixed the suggestions being flagged by dialyzer. 

The code is possibly ready to be merged if you're happy with everything.

**Comment by taylordowns2000** [comment]
hey @NickGowdy , this all looks spot on except for the email change section. I'm getting the following if I attempt to change my email but don't get my current password right (or leave it blank):

```ex
[error] GenServer #PID<0.838.0> terminating
** (FunctionClauseError) no function clause matching in LightningWeb.ProfileLive.FormComponent.handle_event/3
    (lightning 0.1.8) lib/lightning_web/live/profile_live/form_component.ex:19: LightningWeb.ProfileLive.FormComponent.handle_event("save_email", %{"user" => %{"current_password" => "", "email" => "tayssslor@openfn.org"}}, #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, action: :edit, email_changeset: #Ecto.Changeset<action: :validate_email, changes: %{email: "tayssslor@openfn.org"}, errors: [], data: #Lightning.Accounts.User<>, valid?: true>, flash: %{}, id: "97694b9f-0914-4edc-b101-98ed9f6f8422", myself: %Phoenix.LiveComponent.CID{cid: 1}, password_changeset: #Ecto.Changeset<action: :validate_password, changes: %{}, errors: [password: {"can't be blank", [validation: :required]}], data: #Lightning.Accounts.User<>, valid?: false>, return_to: "/profile", title: "Settings", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirmed_at: nil, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, disabled: false, email: "taylor@openfn.org", first_name: "Taylor", id: "97694b9f-0914-4edc-b101-98ed9f6f8422", inserted_at: ~N[2022-07-13 08:17:57], last_name: "Downs", project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, role: :superuser, updated_at: ~N[2022-08-03 12:10:03], ...>}, endpoint: LightningWeb.Endpoint, id: "phx-FwmknhEwBHCgPgRk", parent_pid: nil, root_pid: #PID<0.838.0>, router: LightningWeb.Router, transport_pid: #PID<0.828.0>, view: LightningWeb.ProfileLive.Edit, ...>)
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/channel.ex:600: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.0.0) /Users/taylor/nick/Lightning/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:206: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/channel.ex:523: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17) proc_lib.erl:236: :proc_lib.wake_up/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "15", payload: %{"cid" => 1, "event" => "save_email", "type" => "form", "value" => "user%5Bemail%5D=tayssslor%40openfn.org&user%5Bcurrent_password%5D="}, ref: "19", topic: "lv:phx-FwmknhEwBHCgPgRk"}
State: %{components: {%{1 => {LightningWeb.ProfileLive.FormComponent, "97694b9f-0914-4edc-b101-98ed9f6f8422", %{__changed__: %{}, action: :edit, email_changeset: #Ecto.Changeset<action: :validate_email, changes: %{email: "tayssslor@openfn.org"}, errors: [], data: #Lightning.Accounts.User<>, valid?: true>, flash: %{}, id: "97694b9f-0914-4edc-b101-98ed9f6f8422", myself: %Phoenix.LiveComponent.CID{cid: 1}, password_changeset: #Ecto.Changeset<action: :validate_password, changes: %{}, errors: [password: {"can't be blank", [validation: :required]}], data: #Lightning.Accounts.User<>, valid?: false>, return_to: "/profile", title: "Settings", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirmed_at: nil, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, disabled: false, email: "taylor@openfn.org", first_name: "Taylor", id: "97694b9f-0914-4edc-b101-98ed9f6f8422", inserted_at: ~N[2022-07-13 08:17:57], last_name: "Downs", project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, role: :superuser, updated_at: ~N[2022-08-03 12:10:03], ...>}, %{__changed__: %{}, root_view: LightningWeb.ProfileLive.Edit}, {164395497214658345157977951895481964376, %{1 => {305909518590041931035299644016833524426, %{3 => {101074143988946866529491141524966550769, %{}}}}, 2 => {305909518590041931035299644016833524426, %{3 => {46544817203572658988783113840763960645, %{}}}}}}}}, %{LightningWeb.ProfileLive.FormComponent => %{"97694b9f-0914-4edc-b101-98ed9f6f8422" => 1}}, 2}, join_ref: "15", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, current_user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirmed_at: nil, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, disabled: false, email: "taylor@openfn.org", first_name: "Taylor", id: "97694b9f-0914-4edc-b101-98ed9f6f8422", inserted_at: ~N[2022-07-13 08:17:57], last_name: "Downs", project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, role: :superuser, updated_at: ~N[2022-08-03 12:10:03], ...>, flash: %{}, live_action: :edit, page_title: "Settings", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirmed_at: nil, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, disabled: false, email: "taylor@openfn.org", first_name: "Taylor", id: "97694b9f-0914-4edc-b101-98ed9f6f8422", inserted_at: ~N[2022-07-13 08:17:57], last_name: "Downs", project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, role: :superuser, updated_at: ~N[2022-08-03 12:10:03], ...>}, endpoint: LightningWeb.Endpoint, id: "phx-FwmknhEwBHCgPgRk", parent_pid: nil, root_pid: #PID<0.838.0>, router: LightningWeb.Router, transport_pid: #PID<0.828.0>, view: LightningWeb.ProfileLive.Edit, ...>, topic: "lv:phx-FwmknhEwBHCgPgRk", upload_names: %{}, upload_pids: %{}}
```

Adding a test to the "User edit profile" block in `test/lightning_web/live/profile_live_test.exs` should uncover this error _and_ bump up your test coverage!

FWIW, the errors are handled nicely on the password change section and appear as validation failure warnings on the form when I don't enter my existing password properly.

**Comment by NickGowdy** [comment]
> hey @NickGowdy , this all looks spot on except for the email change section. I'm getting the following if I attempt to change my email but don't get my current password right (or leave it blank):
> 
> ```elixir
> [error] GenServer #PID<0.838.0> terminating
> ** (FunctionClauseError) no function clause matching in LightningWeb.ProfileLive.FormComponent.handle_event/3
>     (lightning 0.1.8) lib/lightning_web/live/profile_live/form_component.ex:19: LightningWeb.ProfileLive.FormComponent.handle_event("save_email", %{"user" => %{"current_password" => "", "email" => "tayssslor@openfn.org"}}, #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, action: :edit, email_changeset: #Ecto.Changeset<action: :validate_email, changes: %{email: "tayssslor@openfn.org"}, errors: [], data: #Lightning.Accounts.User<>, valid?: true>, flash: %{}, id: "97694b9f-0914-4edc-b101-98ed9f6f8422", myself: %Phoenix.LiveComponent.CID{cid: 1}, password_changeset: #Ecto.Changeset<action: :validate_password, changes: %{}, errors: [password: {"can't be blank", [validation: :required]}], data: #Lightning.Accounts.User<>, valid?: false>, return_to: "/profile", title: "Settings", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirmed_at: nil, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, disabled: false, email: "taylor@openfn.org", first_name: "Taylor", id: "97694b9f-0914-4edc-b101-98ed9f6f8422", inserted_at: ~N[2022-07-13 08:17:57], last_name: "Downs", project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, role: :superuser, updated_at: ~N[2022-08-03 12:10:03], ...>}, endpoint: LightningWeb.Endpoint, id: "phx-FwmknhEwBHCgPgRk", parent_pid: nil, root_pid: #PID<0.838.0>, router: LightningWeb.Router, transport_pid: #PID<0.828.0>, view: LightningWeb.ProfileLive.Edit, ...>)
>     (phoenix_live_view 0.17.11) lib/phoenix_live_view/channel.ex:600: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
>     (telemetry 1.0.0) /Users/taylor/nick/Lightning/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
>     (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:206: Phoenix.LiveView.Diff.write_component/4
>     (phoenix_live_view 0.17.11) lib/phoenix_live_view/channel.ex:523: Phoenix.LiveView.Channel.component_handle_event/6
>     (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
>     (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
>     (stdlib 3.17) proc_lib.erl:236: :proc_lib.wake_up/3
> Last message: %Phoenix.Socket.Message{event: "event", join_ref: "15", payload: %{"cid" => 1, "event" => "save_email", "type" => "form", "value" => "user%5Bemail%5D=tayssslor%40openfn.org&user%5Bcurrent_password%5D="}, ref: "19", topic: "lv:phx-FwmknhEwBHCgPgRk"}
> State: %{components: {%{1 => {LightningWeb.ProfileLive.FormComponent, "97694b9f-0914-4edc-b101-98ed9f6f8422", %{__changed__: %{}, action: :edit, email_changeset: #Ecto.Changeset<action: :validate_email, changes: %{email: "tayssslor@openfn.org"}, errors: [], data: #Lightning.Accounts.User<>, valid?: true>, flash: %{}, id: "97694b9f-0914-4edc-b101-98ed9f6f8422", myself: %Phoenix.LiveComponent.CID{cid: 1}, password_changeset: #Ecto.Changeset<action: :validate_password, changes: %{}, errors: [password: {"can't be blank", [validation: :required]}], data: #Lightning.Accounts.User<>, valid?: false>, return_to: "/profile", title: "Settings", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirmed_at: nil, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, disabled: false, email: "taylor@openfn.org", first_name: "Taylor", id: "97694b9f-0914-4edc-b101-98ed9f6f8422", inserted_at: ~N[2022-07-13 08:17:57], last_name: "Downs", project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, role: :superuser, updated_at: ~N[2022-08-03 12:10:03], ...>}, %{__changed__: %{}, root_view: LightningWeb.ProfileLive.Edit}, {164395497214658345157977951895481964376, %{1 => {305909518590041931035299644016833524426, %{3 => {101074143988946866529491141524966550769, %{}}}}, 2 => {305909518590041931035299644016833524426, %{3 => {46544817203572658988783113840763960645, %{}}}}}}}}, %{LightningWeb.ProfileLive.FormComponent => %{"97694b9f-0914-4edc-b101-98ed9f6f8422" => 1}}, 2}, join_ref: "15", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, current_user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirmed_at: nil, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, disabled: false, email: "taylor@openfn.org", first_name: "Taylor", id: "97694b9f-0914-4edc-b101-98ed9f6f8422", inserted_at: ~N[2022-07-13 08:17:57], last_name: "Downs", project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, role: :superuser, updated_at: ~N[2022-08-03 12:10:03], ...>, flash: %{}, live_action: :edit, page_title: "Settings", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirmed_at: nil, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, disabled: false, email: "taylor@openfn.org", first_name: "Taylor", id: "97694b9f-0914-4edc-b101-98ed9f6f8422", inserted_at: ~N[2022-07-13 08:17:57], last_name: "Downs", project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, role: :superuser, updated_at: ~N[2022-08-03 12:10:03], ...>}, endpoint: LightningWeb.Endpoint, id: "phx-FwmknhEwBHCgPgRk", parent_pid: nil, root_pid: #PID<0.838.0>, router: LightningWeb.Router, transport_pid: #PID<0.828.0>, view: LightningWeb.ProfileLive.Edit, ...>, topic: "lv:phx-FwmknhEwBHCgPgRk", upload_names: %{}, upload_pids: %{}}
> ```
> 
> Adding a test to the "User edit profile" block in `test/lightning_web/live/profile_live_test.exs` should uncover this error _and_ bump up your test coverage!
> 
> FWIW, the errors are handled nicely on the password change section and appear as validation failure warnings on the form when I don't enter my existing password properly.

Hey @taylordowns2000 , I'm a bit stuck on the saving email part of the functionality because I don't know how to make the token available in liveview. I tried assigning it and passing the value (like the user struct) but it's never available.

**Comment by NickGowdy** [comment]
> Ack, sorry @NickGowdy . Makes sense and apologies... I forgot we agreed to make a new issue for email change. OK, to wrap up here, please:
> 
> * [ x]  make those email change inputs and buttons disabled. no user fake outs ;-)
> * [x ]  put back `credential_controller.ex` and `credential_controller_test.ex`. (i know I asked you to delete them, but doing so has already hurt us... we don't want anything to do with a `token` in that profile live view... the controller and the controller tests are great cause they show us that it should be `Accounts.apply_user_email(user, password, user_params)` ... confirming via email happens later.
> * [ ]  remove the `Lightning` submodule... I assume. I'm not sure what this is!
> 
> if you add those I'll get this onto main and open up the next issue for email. i'll tag you there if you're interested!

Hey @taylordowns2000,

I've restored the `user_settings_controller` and it's tests and I changed the route for now so they don't clash. I've also added a unit test for validate email (It wasn't actually rendering the message on change...).

I'm not sure what you mean by Lightning module, could you point that out and I'll make that last change.

Cheers
Nick

**Comment by taylordowns2000** [comment]
Brilliant, all green checks @NickGowdy !

The Lightning module is [this](https://github.com/OpenFn/Lightning/pull/218/files#diff-41e68f2cdb3806bb899cb2f3c3d80a2171f37c85b60e8e486742234e4e5f5738)... up at the top of the "files changed" part of your PR. Looks like a git submodule? (Which I am no expert in, but if it was unintentional it should be removed from the PR before we merge.)

image

**Comment by NickGowdy** [comment]
How weird, I must of added that by accident.

I've removed that so I think we're all good for this branch?

**Pull request merged**
