### PR TITLE
Combobox As Scope Picker

### PR DESCRIPTION
**Pull request by elias-ba**
### Description

This PR enhances the project picker by converting it into a more generic combobox component. The new combobox allows users to search for projects by typing directly into the input field. Additionally, the project picker has been moved to the Common module and refactored to support a broader range of item types, not just projects.

Re [#241](https://github.com/OpenFn/thunderbolt/issues/241)

### Validation steps

1. Launch the app
2. Start typing a project name in the project picker
3. See how it filters out the projects that matches your search query
4. Click on the chevron buttons to display the list of the projects
5. Click on a project to pick it

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
@elias-ba to touch up [these 4 items](https://openfn.slack.com/archives/C05KZNPEJFN/p1724664831338139?thread_ts=1724663961.260279&cid=C05KZNPEJFN)

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
so close! really looks wonderful. needs to select/allow enter-press as you type. that's it. everything else is great. here's the requirement: https://www.loom.com/share/af341c8de21b4c3984eca1c6cd86d47d

**Comment by elias-ba** [comment]
Thanks for the review, @taylordowns2000! I've implemented the ability to use the Enter key to select an item. Additionally, you can now navigate through the items using the up and down arrow keys on your keyboard.

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
still pretty close!

use the combobox on tailwind components for a few minutes, then use your implementation. hard to explain all the little bits, so tried another video:
https://www.loom.com/share/04544429797e4649bd32236f4ba7f9f8

it's very good and very close, but still a couple of things that aren't right.

1. you shouldn't be able to highlight two things at once (keyboard vs mouse!?!)
2. if you've got "abc" in the text box, abc should be selected and highlighted
3. clicking _anywhere_ on the dropdown should produce the same opening behaviour... don't separate the behaviour between the side button and the text input part

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
does not look like my second review tonight was addressed: https://github.com/OpenFn/lightning/pull/2424#pullrequestreview-2264132637

**Comment by elias-ba** [comment]
@taylordowns2000 I fixed your change requests. I also compared my version of the combobox with the Tailwind one, they are pretty similar now. Could you give me another round of review please ?

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
not quite there. still able to select 2 at a time. maybe a quick sync with @stuartc to get this over the line?

image

**Review by taylordowns2000 — APPROVED** [review]
great job!

**Pull request merged**
