### PR TITLE
Fix code editor cursor resetting it's position

### LINKED ISSUE #2007: Manage how workflow canvas auto refreshes and results to loss of unsaved changes
There are moments when the workflow canvas automatically refreshes due to a web socket disconnection, bad internet connection, or if the app is left idle for 6 minutes. When the socket disconnects and the refresh happens, unsaved changes are lost. This is a very frustrating experience for the user. 

A few questions here: 
-  Is the socket connection loss ideal? Can we stop it?
- If we can't stop it, how do we fix the mount/reconnect process to ensure that we don't lose unsaved changes

### From @stuartc :
`Caddyfile`
```
:8080 {
    reverse_proxy host:4000 {
      stream_timeout 30s
    }
}
```
Run
```
docker run --rm -t \
  --add-host host:10.0.0.47 \
  -v $PWD/Caddyfile:/etc/caddy/Caddyfile \
  -p 8080:8080 \
  caddy:2.8.4
```

For futher debugging locally, I recommend the approach above, where you run your dev server, and put it behind caddy...
Change the `--add-host` to your local IP.
And change the stream timeout to anything between 30s and like 120s..

That will give you a small portion of the conditions for websockets getting disconnected..

You can access the app at `localhost:8080` vs `:4000`

### LINKED ISSUE #2229: Jumpy cursor in job editor
Lightning v2.7.0 

The cursor jumps to a different line when typing into the job editor. See the video below to see this behavior.

https://www.loom.com/share/d98448190ecf42e5954e907fefe9150f?sid=54b65540-737c-44ab-ac32-0f19bdabf142

### PR DESCRIPTION
**Pull request by stuartc**
## Validation Steps

- Edit any job and start typing relatively quickly.
- The cursor should no jump to the end of the document.

> To further emphasis the issue, create a Network profile in the browser debug tools, bandwidth doesn't matter that much, but go for 200+ ms of latency.

https://github.com/OpenFn/lightning/assets/144796/0cf61bd3-5829-4c10-a0e7-f8a6eed8ba68

This PR also includes significant changes in how data is sync'd with the server.

Special attention should be paid to editing jobs, and combinations of saving and not saving while moving around different jobs.

Also attention should be paid to the recent snapshot UI changes, as the editors body/text is not getting its data directly via the html data attributes anymore.

I have added a function onto the `window` object for testing the behaviour of socket reconnects. To use it open the browser devtools and call the `triggerReconnect()` function which closes the socket and reconnects after 5 seconds, which appears to reproduce the same behaviour when you're online.

## Details

Rework of editor state syncing

- The editor now gets it's text body from the WorkflowEditorHook's store.
- It also sends it's changes to LiveView via the `proposeChanges` API which sends diffs.
- Added an online/offline indicator to the WorkflowEdit page.
- Disabled and reenable Save buttons when the socket is reconnecting.
- Added a warning that closing the JobEditor during a reconnect will lose changes (since a live patch link behaves like a regular link when disconnected)
- added a `reconnected` callback to WorkflowEditor that does a diff against the new (outdated) state from the server and sends back diffs to update the server, maintaining the users changes across socket reconnects

## Related issue

Fixes #2229 
Fixes #2007

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

**Review by christad92 — APPROVED** [review]

**Comment by christad92** [comment]
Thanks @stuartc! it looks good to me.

**Comment by stuartc** [comment]
This introduces a regression with the recent snapshot edit changes. Not ready to merge!

**Comment by taylordowns2000** [comment]
> This introduces a regression with the recent snapshot edit changes. Not ready to merge!

Hey @stuartc , does this latest set of changes address the above? (Good to merge if everything looks good?)

**Comment by stuartc** [comment]
> > This introduces a regression with the recent snapshot edit changes. Not ready to merge!
> 
> Hey @stuartc , does this latest set of changes address the above? (Good to merge if everything looks good?)

Yep, the changes committed today address that regression I introduced by trying to fix another regression. 🤣

**Pull request merged**
