### PR TITLE
Documentation: Troubleshooting NodeJS dns resolution for localhost

### PR DESCRIPTION
**Pull request by bensonmiller**
## Notes for the reviewer
This is a pure documentation PR related to Lightning workers and NodeJS DNS name resolution. I've added a few lines to the bottom of the `WORKERS.md` to help users troubleshoot situations where Workers aren't connecting to Lightning due to NodeJS DNS resolution behavior changes in NodeJS v17. I bumped into this issue a couple days ago and it took a little digging to diagnose and resolve. I hope this PR helps someone else.

## Related issue

No associated issues.

## Review checklist

As this PR is pure documentation, I haven't haven't done any code review or QA. I also haven't modified the CHANGELOG.

### CODE REVIEW

**Review by stuartc — COMMENTED** [review]
Thanks so much for this @bensonmiller!

Could I ask you to run this through a formatter, I think prettier handles markdown files - it will keep the line width at 80 chars.

Perhaps it might be helpful that (when dev'ing locally) you can use a NodeJS env var to change the network stack ordering like this: `NODE_OPTIONS=--dns-result-order=ipv4first` 

Since the worker runs as a child process in development mode, it will inherit that env variable and you don't need to run the worker in a separate shell.

**Comment by bensonmiller** [comment]
@stuartc  - Absolutely. I'll make it `prettier` and add that helpful node regarding `NODE_OPTIONS`.

**Comment by bensonmiller** [comment]
@stuartc  -- PR updated per your suggestions and ready for a re-inspection. Thank you!

**Review by stuartc — APPROVED** [review]
Awesome! Thank you!

**Pull request merged**
