### PR TITLE
Add API Version field in Salesforce OAuth credentials

### LINKED ISSUE #1838: Additional fields on the salesforce oauth credential
### Description
Add support additional fields on the salesforce oauth credential. Eg `apiVersion`

### Additional context
In salesforce configuration schema, you have an option of setting `apiVersion`. This enable the salesforce client to use the specified `apiVersion` instead of the default one. [See salesforce configuration schema](https://docs.openfn.org/adaptors/packages/salesforce-configuration-schema#sample-configuration)

### PR DESCRIPTION
**Pull request by elias-ba**
## Validation Steps

1. Create a Salesforce OAuth credential
2. See the API Version field rendered under the scopes
3. Create the credential with an API Version value
4. Edit your newly created credential and see the value of the API Version rendered correctly

## Related issue

Fixes #1838 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

### CODE REVIEW

**Comment by stuartc** [comment]
@taylordowns2000 I've given this a cursory glance, it looks fine - if the review/testing goes well please merge it.

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
hi @elias-ba , this doesn't look like it works: https://www.loom.com/share/67a667d1a8b6466e8446badc75aecbd8

am i doing something wrong?

**Comment by christad92** [comment]
> hi @elias-ba , this doesn't look like it works: https://www.loom.com/share/67a667d1a8b6466e8446badc75aecbd8
> 
> am i doing something wrong?

@elias-ba I think this might be related to Taylor's comment above. https://www.loom.com/share/417c7edcfba34baa9f9ef971a8909cb0?sid=419094e7-512c-4fbc-b6eb-607ad9c0cc09

**Comment by elias-ba** [comment]
@taylordowns2000 I just pushed a changes that fixes the problem of api_version when editing a SF OAuth credential. Please test again and let me, all looks good from my side.

Hey @christad92 that error you see is unrelated to the OAuth thing. It is a feature that Roger introduced last week and that is basically avoid being able to access the credential edit page in two different tabs. Did you have 2 tabs opened ?

**Comment by christad92** [comment]
Hey @elias-ba I have pulled the fix and it seems to be find if I was editing from the  profile -> Credentials-> edit path but throws the "project was updated in another session. try again"  error when I try via the project -> settings -> credentials -> edit. I have just one instance tab running.

**Comment by elias-ba** [comment]
@christad92 you probably caught a bug that needs to go to a new issue and I am happy to fix it when that is done. By as I said earlier that behaviour you are seeing there is actually coming from a feature shipped [here](https://github.com/OpenFn/lightning/pull/1830)

**Comment by taylordowns2000** [comment]
@jyeshe - can you help here? I think that's your error message 😊

**Comment by jyeshe** [comment]
> @jyeshe - can you help here? I think that's your error message 😊

Hi @taylordowns2000 , hey @elias-ba this means that there is another process updating the credential (which would make the assign to be outdated compared to db) or the credential assign is not updated. This [PR](https://github.com/OpenFn/lightning/pull/1862) updates it here and make the comparison less strict for the purpose of avoiding `on_replace: :raise` error when project_credentials gets stale.

**Comment by taylordowns2000** [comment]
@elias-ba , what's the status on this guy? ready to go?

**Comment by christad92** [comment]
@taylordowns2000 I have QA'd this and it is good to go.

**Review by taylordowns2000 — APPROVED** [review]

**Review by christad92 — APPROVED** [review]
Tested and it works. LGTM.

**Pull request merged**
