### PR TITLE
Restore integration tests

### LINKED ISSUE #2187: Enable End to End Integration tests
We need to enable end-to-end integration tests on Lightning to improve our confidence in the features released for testing and reduce potential gotchas as engineers can't manually test all edge cases when introducing changes to the codebase. 

These tests were turned off at some point because they were failing but we don't know what they are failing. 

PS: We also need guidance on the _ethical_ exclusion of integration tests when devving.

### PR DESCRIPTION
**Pull request by midigofrank**
### Description

Ensures 

Closes #2187

### Validation steps

Run `mix test test/integration`

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.

### CODE REVIEW

**Review by taylordowns2000 — APPROVED** [review]
this is passing for @elias-ba , @midigofrank , and on CI so I'm approving but noting that i can't get it to work locally—i'll sort my stuff out later, better to get integration tests back on CI asap

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
ooops, i was wrong. this is failing for @elias-ba and for me. let's fix before merging so we don't slow down other engineers

**Review by elias-ba — CHANGES_REQUESTED** [review]
When I run the tests, I have 3 out 5 failing. Could this be my local setup ? Cause they seem to pass on CI
image

**Comment by midigofrank** [comment]
@elias-ba yes it could be something/configuration on your local setup. I'll clone the repo afresh and test this to see if I can get the same failures.

**Comment by elias-ba** [comment]
Yes ! @midigofrank @taylordowns2000 it was related to my previously set env variables `OPENFN_API_KEY` and `OPENFN_ENDPOINT`. When I unset them, the tests are all green.

**Review by elias-ba — APPROVED** [review]
@midigofrank great job 👏🏽 . The tests are passing successfully. The failures were related to my local configs

**Pull request merged**
