### PR TITLE
chore: Update local randomUUID generation over crypto randomUUID

### LINKED ISSUE #2361: Create new workflow under certain network conditions (crypto on http, rather than https or localhost)
Creating a new workflow in an `http` environment (using server ip address on browser) fails as the `cypto.randomUUID()` function requires a `localhost` or `https` environment only.

### PR DESCRIPTION
**Pull request by ibrahimwickama**
### Description

This PR *fixes an issue of workflow generation when creating new workflow on http environment(using server ip address on browser, the cypto.randomUUID() function requires a localhost or https environment only)*

fixes #2361

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [ ] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [ ] I have updated the **changelog**.

### CODE REVIEW

**Comment by taylordowns2000** [comment]
@ibrahimwickama , this is great, thank you! and i did not know that `cypto.randomUUID()` only works in https or localhost.

just to clarify, is the reason you're using http that it's all running behind secure infra? excited to chat tomorrow.

**Comment by midigofrank** [comment]
Interesting. I didn't know about this as well: https://stackoverflow.com/questions/74911304/crypto-module-not-loading-randomuuid-when-viewing-a-local-network-ip-address

**Review by midigofrank — APPROVED** [review]
Nicely done

**Comment by josephjclark** [comment]
This looks great - I had no idea about any of this.

I'd like to run a couple of tests before releasing. I'll do that this morning

**Review by josephjclark — APPROVED** [review]
Generated 10 million UUIDs locally (a couple of times actually) - all unique :+1: 

The algorithm seems to be floating around stackoverflow. I know nothing about cryptography but it looks fine to me. Usually I'd recommend using a library for this sort of thing but I'm happy enough in this case

**Comment by taylordowns2000** [comment]
fixes #2361

**Comment by taylordowns2000** [comment]
thanks @ibrahimwickama ! really appreciate it ❤️

**Comment by ibrahimwickama** [comment]
Am glad to help guys, @taylordowns2000 @josephjclark @midigofrank

**Pull request merged**
