### PR TITLE
Disabling credential transferring feature for Beta.

### LINKED ISSUE #507: Avoid showing all users
### User story
As someone that has created an account on OpenFn demo, I would like to be sure that no one else can see my username or email, for security/privacy purposes

### Details
Comment out the code for credential transfer (see screenshot below)

### Implementation notes

- Credential transfer should be DISABLED for beta.
- Later, we should allow credential transfer via email text entry (rather than pick list) for multi-tenant deployments.

### Release notes
Temporarily remove credential ownership transfer

### User acceptance criteria
There is nowhere in Lightning that I can see a list of existing users (unless I am a superuser).

### PR DESCRIPTION
**Pull request by elias-ba**
## Related issue

Fixes #507 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If needed, I've updated the changelog
- [x] Amber has QA'd this feature

### CODE REVIEW

**Comment by amberrignell** [comment]
Nice one, the story has been met.
Just a quick thought:  there are a couple of things we are removing/hiding for beta it may be nicer to hide these behind a flag rather than having commented out code in our repository 🤷

**Review by amberrignell — APPROVED** [review]

**Comment by stuartc** [comment]
> Nice one, the story has been met. Just a quick thought: there are a couple of things we are removing/hiding for beta it may be nicer to hide these behind a flag rather than having commented out code in our repository shrug

@amberrignell I agree here...

Sorry @elias-ba, could you put this behind a feature flag?

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
@elias-ba , looking good. please:
1. make the feature flag use an environment variable. (see how this is done elsewhere. it's no good creating the flag but then not having it hard-coded to `false` in `confix.exs`)
2. change the changelog.md. you're not "removing credential ownership transfer" it in lightning, you are "Allowing credential ownership transfer to be enabled or disabled with an environment variable."
3. remove the changes to `test.exs` as they won't be necessary after you've set up your .env variable defaulting to true
4. change line 81 of `config.exs` to explain that the default is true but that it reads your system env for disabling. (lightning, this app, doesn't care about "beta" or where it's deployed.)

@amberrignell , check out the requested changes above... for you the most important ones are around the change log!

**Review by stuartc — APPROVED** [review]

**Comment by stuartc** [comment]
> @elias-ba , looking good. please:
> 
> 1. make the feature flag use an environment variable. (see how this is done elsewhere. it's no good creating the flag but then not having it hard-coded to `false` in `confix.exs`)
> 2. change the changelog.md. you're not "removing credential ownership transfer" it in lightning, you are "Allowing credential ownership transfer to be enabled or disabled with an environment variable."
> 3. remove the changes to `test.exs` as they won't be necessary after you've set up your .env variable defaulting to true
> 4. change line 81 of `config.exs` to explain that the default is true but that it reads your system env for disabling. (lightning, this app, doesn't care about "beta" or where it's deployed.)
> 
> @amberrignell , check out the requested changes above... for you the most important ones are around the change log!

Eish, sorry @taylordowns2000 I merged without reading this.

1. I asked that this not be an environment variable since I don't see it as a facility we are going to turn on and off during runtime - the previous solution was to comment out the functionality; so going on that solution I see us removing the flag and reinstating the feature.
2. I'll update the CHANGELOG since I'm the one who merged this prematurely.
3. I guess 1 and 2 apply here too.

**Pull request merged**
