### PR TITLE
Auth and dash UI improvements

### PR DESCRIPTION
**Pull request by Ngizeh**
## Notes for the reviewer

User authorization and home dashboard UI refactor.

## Related issue

Fixes #

## Checklist before requesting a review

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Amber has **QA'd** this feature

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
Hi @Ngizeh , thanks so much for suggesting these changes. I absolutely love the UI direction... it starts to get at #755 in a really lovely way. There are a few things to address before we could merge this, but I think it's a great start.

1. There seem to be a number of unintentional (maybe auto-generated?) changes to files that should not be impacted by this work. See `layout_components.ex` for an example. In several places tailwind classes get re-ordered. In other places, `~p"/profile"` gets re-written to `Routes.profile_edit_path(@socket, :edit)`. Elsewhere, I see `attr :text, :string, required: false` getting edited to `attr(:text, :string, required: false)`. Please make sure to review your code before opening the PR. If you've got strong opinions about why you'd like to introduce these changes, articulate them in the PR. Otherwise, please revert the unintentional stuff so it doesn't create a diff against `main`.
2. I'm seeing that the job inspector panel got messed up. (See first image below.) Are you seeing this same behavior? If so, please amend the PR so it doesn't impact the job panel.
3. `12%` is hardcoded. What does this metric represent? Please either _connect it_ and propose a reason for its inclusion or remove it entirely. (I really do love the design, but we can't merge something into `main` that's misleading and/or knowingly broken.)
4. Does the `:search_by_name` feature work for you? I can't get it to actually filter the workflows on that index page.
5. It looks like you've commented out the `delete a workflow on project index page` test. Please hook this back up, making whatever changes are necessary, to ensure that this feature is properly preserved.

Thanks again. Really cool stuff here and I hope we can get your contributions merged soon ❤️

**Comment by Ngizeh** [comment]
HI @taylordowns2000 I have fixed the issues you raised, mostly the Editor auto-generated changes. 
Please review the implemented behavior on the dashboard. Let me know your views before merging with the main branch.

**Comment by taylordowns2000** [comment]
@Ngizeh , so sorry for the delay here. Our team got quite busy and we haven't been able to prioritize this. Our CTO did mention that, for future PRs, it's generally easier to get them reviewed and merged if the distinct bits of functionality (or new designs) you propose are split up into separate PRs.

Again, sorry to go quiet here! Hope you're doing well.

**Comment by Ngizeh** [comment]
@taylordowns2000 Thank you for reaching out I am very well. Totally agree I will separate this PR into bits for easier and faster review.

**Pull request closed without merging**
